# Generated by Django 5.2.15 on 2026-06-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('parent_number', models.IntegerField()),
                ('parent_email', models.EmailField(max_length=254)),
                ('present_address', models.TextField()),
                ('parmanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('student_class', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('addmission_number', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
            ],
        ),
    ]
