# Generated by Django 5.2.15 on 2026-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_number',
            field=models.CharField(max_length=20),
        ),
    ]
